name: Sync Gitee

on:
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * *

jobs:
  sync:
    name: Sync Gitee
    env:
      gitee_repo: ${{ secrets.GITEE_REPO }}
      gitee_token: ${{ secrets.GITEE_TOKEN }}
      gitee_user: ${{ secrets.GITEE_USER }}
      gitee_branch: ${{ secrets.GITEE_BRANCH }}

    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add Gitee remote and sync
      run: |
        git remote add gitee https://${{ env.gitee_user }}:${{ env.gitee_token }}@gitee.com/${{ env.gitee_user }}/${{ env.gitee_repo }}.git
        git fetch origin ${{ env.gitee_branch }}
        git push --force gitee ${{ env.gitee_branch }}:${{ env.gitee_branch }}
