name: Sync Gitee

on:
  push:
    branches:
      - master

jobs:
  repo-sync:
    name: Sync Gitee
    env:
      dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
      dst_token: ${{ secrets.GITEE_TOKEN }}
      gitee_user: ${{ secrets.GITEE_USER }}
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Sync Gitee
        uses: Yikun/hub-mirror-action@master
        if: env.dst_key && env.dst_token && env.gitee_user
        with:
          src: 'github/${{ github.repository_owner }}'
          dst: 'gitee/${{ secrets.GITEE_USER }}'
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token:  ${{ secrets.GITEE_TOKEN }}
          static_list: ${{ github.event.repository.name }}
          mappings: "z=>zz"
          force_update: true
